### ISSUE TITLE
Класс GameStore не создает игру с заданными параметрами

### ISSUE THREAD

**Issue by AlenaZaglada** [Evgeniakoch/TeamProject#2]
#Описание
В методе publishGame в классе GameStore не создается игра с заданными жанром и заголовком

#Локация дефекта
https://github.com/Evgeniakoch/TeamProject/blob/964f7d6a566f9c90feef377b0173476586680a3e/src/main/java/ru/netology/GameStore.java#L22

#Шаги воспроизведения
1. Открыть [код программы](https://github.com/Evgeniakoch/TeamProject/blob/964f7d6a566f9c90feef377b0173476586680a3e/src/test/java/ru/netology/GameStoreTest.java#L36) в IDEA
2. Запустить тест shouldContainsGame
3. Посмотреть на вывод в консоли 

*Ожидаемый результат*: true
*Фактический результат*: false

#Скриншот
![image](https://user-images.githubusercontent.com/121796172/228526298-efe3586f-4c57-45b8-8adb-88bb47a7d1b5.png)

#Окружение
* **Операционная система:** Windows 10Pro
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Evgeniakoch** [comment]
Баг исправлен. Метод containsGame исправлен

![image](https://user-images.githubusercontent.com/122497660/229400557-ee3ade87-7a43-4770-8a70-81842b662e81.png)
