### ISSUE TITLE
Общее количество времен всех игроков не суммируется

### ISSUE THREAD

**Issue by AlenaZaglada** [Evgeniakoch/TeamProject#3]
# Описание
В классе GameStore при выполнении теста shouldSumPlayedTime1 не суммируется общее количество времени игроков, которое они провели за играми каталога

# Локация дефекта
https://github.com/Evgeniakoch/TeamProject/blob/964f7d6a566f9c90feef377b0173476586680a3e/src/main/java/ru/netology/GameStore.java#L75

# Шаги воспроизведения
1. Открыть [тест](https://github.com/Evgeniakoch/TeamProject/blob/964f7d6a566f9c90feef377b0173476586680a3e/src/test/java/ru/netology/GameStoreTest.java#L48) в IDEA
2. Запустить тест 
3. Посмотреть на вывод консоли

*Ожидаемый результат:* 7
*Фактический результат:* 0

# Скриншот 
![image](https://user-images.githubusercontent.com/121796172/228912607-5ce81e81-325b-4740-8a60-b0c7191faab6.png)

# Окружение
* **Операционная система:** Windows 10Pro
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Evgeniakoch** [comment]
Баг исправлен.
Метод getSumPlayedTime дописан в соответствии с требованиями.

![image](https://user-images.githubusercontent.com/122497660/229411800-c1d111b9-dfe7-49b1-bc7c-fa99642802c2.png)
