### ISSUE TITLE
Метод containsGame неправильно проверяет наличие игры в каталоге

### ISSUE THREAD

**Issue by AlenaZaglada** [Evgeniakoch/TeamProject#4]
# Описание
В классе GameStore метод containsGame при проверке наличия игры не обнаруживаются. Хотя ранее игры были добавлены с помощью метода publishGame.

# Локация дефекта
https://github.com/Evgeniakoch/TeamProject/blob/964f7d6a566f9c90feef377b0173476586680a3e/src/main/java/ru/netology/GameStore.java#L32

# Шаги воспроизведения
1. Открыть [тест](https://github.com/Evgeniakoch/TeamProject/blob/964f7d6a566f9c90feef377b0173476586680a3e/src/test/java/ru/netology/GameStoreTest.java#L9) в IDEA
2. Запустить тест 
3. Посмотреть на вывод консоли

*Ожидаемый результат:* true
*Фактический результат:* false

# Скриншот 
![image](https://user-images.githubusercontent.com/121796172/228956391-c2bd9da3-31d5-47bc-a69f-f3dfa2c47304.png)

# Окружение
* **Операционная система:** Windows 10Pro
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Evgeniakoch** [comment]
Данный тест является дубликатом теста №2, потому что в обоих тестах проверяется один и тот же метод на true/false  c одними и теми же входными данными.
