### ISSUE TITLE
Количество времени, которое игрок провел за игрой не регистрируется

### ISSUE THREAD

**Issue by AlenaZaglada** [Evgeniakoch/TeamProject#5]
# Описание
В классе GameStoreTest при выполнении теста playTimeCheck не регистрируется количество времени, которое игрок провел за игрой этого каталога

# Локация дефекта
https://github.com/Evgeniakoch/TeamProject/blob/964f7d6a566f9c90feef377b0173476586680a3e/src/main/java/ru/netology/GameStore.java#L46

# Шаги воспроизведения
1. Открыть [тест](https://github.com/Evgeniakoch/TeamProject/blob/964f7d6a566f9c90feef377b0173476586680a3e/src/test/java/ru/netology/GameStoreTest.java#L18) в IDEA
2. Запустить тест 
3. Посмотреть на вывод консоли

*Ожидаемый результат:* 7
*Фактический результат:* 0

# Скриншот 
![image](https://user-images.githubusercontent.com/121796172/228960766-9009e57c-c8e6-4b5d-8720-e1d94059322e.png)

# Окружение
* **Операционная система:** Windows 10Pro
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Evgeniakoch** [comment]
Дебагером выявлена ошибка в методе addPlayedTime. Метод исправлен.
![image](https://user-images.githubusercontent.com/122497660/229412249-e9f35e41-60e9-402c-8844-d17ba6b53134.png)
