### ISSUE TITLE
Возвращается null при поиске жанра в который играли больше всего (NullPointerException)

### ISSUE THREAD

**Issue by Evgeniakoch** [Evgeniakoch/TeamProject#6]
# Описание
При попытке получить название игры по жанру, в которую Player поиграл больше всего, возвращается null, т.к. метод не дописан.

# Локация
https://github.com/Evgeniakoch/TeamProject/blob/5a99e00b600cdc844839a09ae15aed1c863f4f52/src/test/java/ru/netology/PlayerTest.java#L81

# Шаги воспроизведения:
1. Открыть в IDEA код командного проекта PlayerTest.java
2. Запустить тест shouldReturnTimeMostPlayedByGenre
3. Запустить Дебагер с 87 строчки
4. Перешагнуть
5. Посмотреть на переменную i, которой присвоилось значение null

*Ожидаемый результат*: Название (Title) игры warcraft
*Фактический результат*: null

# Скриншот
![image](https://user-images.githubusercontent.com/122497660/229289766-35ef7cde-5fc4-4411-9f73-83063d41882e.png)

# Окружение

Операционная система: Windows 10Pro
IDE: IntelliJ IDEA 2020.2 (Community Edition)
Java: OpenJDK 11

**Comment by AlenaZaglada** [comment]
shouldReturnTimeMostPlayedByGenre исправлен

**Comment by Evgeniakoch** [comment]
Тест не проходит. 
![image](https://user-images.githubusercontent.com/122497660/229686417-030d90d4-54eb-4dbc-bb91-fef53857ab66.png)

**Comment by AlenaZaglada** [comment]
Код исправлен, тест проходит
