### ISSUE TITLE
Если игра не была установлена, не выкидывается RuntimeException

### ISSUE THREAD

**Issue by Evgeniakoch** [Evgeniakoch/TeamProject#7]
# Описание
По требованиям в методе play, если игра не была установлена, то надо выкидывать RuntimeException

# Локация дефекта
https://github.com/Evgeniakoch/TeamProject/blob/90f5ce6e1072614e48e3401db411dba49985af6b/src/test/java/ru/netology/PlayerTest.java#L49

# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Запустить тест shouldThrowRuntimeExceptionIfGameNotInstalled
3. Прочитать вывод консоли

*Ожидаемый результат* - RuntimeException
*Фактический результат* - RuntimeException не выбрасывается

![image](https://user-images.githubusercontent.com/122497660/229687944-694cda7f-8b3a-4a0a-8501-ae2992d4ee6f.png)

# Окружение:
Операционная система: Windows 10Pro
IDE: IntelliJ IDEA 2020.2 (Community Edition)
Java: OpenJDK 11

**Comment by AlenaZaglada** [comment]
Код исправлен. Добавлен класс NotInstalledException
