### ISSUE TITLE
Не суммируется время игры по жанру в методе sumGenre

### ISSUE THREAD

**Issue by Evgeniakoch** [Evgeniakoch/TeamProject#8]
# Описание
Время игры в игру по жанру не суммируется

# Локация
https://github.com/Evgeniakoch/TeamProject/blob/058f4350e2f2a07095db89c4d0ecebbde630e703/src/test/java/ru/netology/PlayerTest.java#L74

# Шаги воспроизведения
1. Открыть код программы в IDEA
2. Запустить тест shouldSumPlayedTimeByGenre
3. Проанализировать вывод консоли

# Скриншот
![image](https://user-images.githubusercontent.com/122497660/229690172-42005d81-58cd-42df-9ee2-cfd608d0ca51.png)

# Окружение
Операционная система: Windows 10Pro
IDE: IntelliJ IDEA 2020.2 (Community Edition)
Java: OpenJDK 11

**Comment by AlenaZaglada** [comment]
код исправлен
