### ISSUE TITLE
Метод play не суммирует время игры в игру по жанру

### ISSUE THREAD

**Issue by Evgeniakoch** [Evgeniakoch/TeamProject#9]
# Описание
Метод play по требованиям должен возвращать суммарное количество часов, проигранное в определенную игру, но в итоге не суммирует время

# Локация 
https://github.com/Evgeniakoch/TeamProject/blob/058f4350e2f2a07095db89c4d0ecebbde630e703/src/test/java/ru/netology/PlayerTest.java#L60

# Шаги воспроизведения 
1. Запустить код программы в IDEA
2. Запустить тест shouldSumPlayedTime
3. Посмотреть вывод на консоли

*Ожидаемый результат* - 15
*Фактический результат* -  5 

# Скриншот
![image](https://user-images.githubusercontent.com/122497660/229692229-d5fa1bad-179a-4be7-b1f8-fb8e3935163a.png)

# Окружение
Операционная система: Windows 10Pro
IDE: IntelliJ IDEA 2020.2 (Community Edition)
Java: OpenJDK 11

**Comment by AlenaZaglada** [comment]
код исправлен
